# Generated by Django 5.0.2 on 2024-03-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('resolved', 'RESOLVED')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=60)),
                ('package_publish_date_time', models.DateTimeField(auto_now=True)),
                ('package_status', models.CharField(max_length=60)),
                ('package_price', models.FloatField()),
                ('package_duration', models.IntegerField()),
                ('package_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Securitytechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('resolved', 'RESOLVED')], max_length=60)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('completed', 'COMPLETED'), ('pending', 'PENDING')], max_length=60)),
                ('package_purchase_date', models.DateTimeField()),
                ('transactionid', models.CharField(max_length=100)),
                ('premium_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=60)),
                ('document_title', models.CharField(max_length=60)),
                ('document_description', models.TextField()),
                ('document_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], max_length=60)),
                ('document_size', models.FloatField()),
                ('document', models.FileField(upload_to='')),
                ('document_publish_date_time', models.DateTimeField(auto_now=True)),
                ('document_password', models.CharField(max_length=60)),
                ('document_bin', models.IntegerField()),
                ('document_sent', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('document_security_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.securitytechnique')),
            ],
        ),
        migrations.CreateModel(
            name='Usercarddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Userpackagedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_status', models.CharField(choices=[('active', 'ACTIVE'), ('expired', 'EXPIRED')], max_length=60)),
                ('package_purchase_date', models.DateTimeField(auto_now=True)),
                ('package_expiry_date', models.CharField(max_length=60)),
                ('premium_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
