# Generated by Django 5.0.2 on 2024-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_documentprivilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_bin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_password',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_sent',
            field=models.IntegerField(default=0),
        ),
    ]
