# Generated by Django 5.0.2 on 2024-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_document_document_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='login',
            name='lname',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
