# Generated by Django 5.0.2 on 2024-03-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_name_login_fname_login_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='fname',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
