# Generated by Django 5.0.2 on 2024-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_feedback_rename_name_inquiry_lname_inquiry_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
