# Generated by Django 5.0.2 on 2024-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_document_document_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=60)),
                ('package_publish_date_time', models.DateTimeField(auto_now=True)),
                ('package_status', models.CharField(max_length=60)),
                ('package_price', models.FloatField()),
                ('package_uploads', models.IntegerField()),
                ('file_size', models.FloatField()),
                ('package_duration', models.IntegerField()),
                ('package_description', models.TextField()),
            ],
        ),
    ]
