# Generated by Django 5.0.2 on 2024-04-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_testpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='file_size',
            field=models.BigIntegerField(),
        ),
    ]
