# Generated by Django 5.0.2 on 2024-04-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_userpackagedetails_premium_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackagedetails',
            name='premium_package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package'),
        ),
    ]
