# Generated by Django 5.0.2 on 2024-04-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userpackagedetails_premium_package_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testPackage',
        ),
        migrations.AddField(
            model_name='package',
            name='file_size',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='max_uploads',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
