# Generated by Django 5.0.2 on 2024-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_package_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_uploads',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
