# Generated by Django 5.0.2 on 2024-04-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_package_file_size_alter_package_max_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercarddetails',
            name='expiry_date',
            field=models.CharField(max_length=10),
        ),
    ]
