# Generated by Django 5.0.2 on 2024-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_usercarddetails_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
