# Generated by Django 5.0.2 on 2024-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
